# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZc8sAxissjho5JrOmA2TEq-3wALptHq
"""

print("Hello, I am your memory center")

memory = []

def save_memory(text):
    memory.append(text)
    print("Saved:", text)

save_memory("My name is [YOUR NAME]")
save_memory("I want to build AI assistant")
save_memory("I am learning Python")

def show_all_memories():
  print("---MY MEMORIES ---")
  for i, memory_item in enumerate(memory):
    print(f"{i+1}. {memory_item}")
show_all_memories()

import json
def save_to_file(memory_list):
  with open('memories.json' ,'w') as f:
    json.dump(memory_list, f)
  print("Memories saved to file !")

def load_from_file():
  try:
    with open('memories.json' , 'r') as f :
      return json.load(f)
  except:
    return []
# Test it
memory = load_from_file()
memory.append("I am building a memory center")
save_to_file(memory)

def add_memory(text):
  memories = load_from_file()
  memories.append(text)
  save_to_file(memories)
  print(f"Added: {text}")

def show_memories():
  memories = load_from_file()
  if not memories :
   print("No memories yet!")
  else:
    print("--- YOUR MEMORIES ---")
    for i, m in enumerate(memories):
      print(f"{i+1}. {m}")

#Test
add_memory("I am learning Python")
show_memories()

def delete_memory(number) :
  memories = load_from_file()
  if 0 < number < len(memories):
    removed = memories.pop(number - 1)
    save_to_file(memories)
    print(f"Deleted: {removed} ")
  else:
    print("Invalid number")

# Test - show memories first then delete one
show_memories()
delete_memory(1)
show_memories()

import requests

def chat_with_anastasiya(your_message):

    memories = load_from_file()
    memory_text = "\n" .join([f"-{m}"for m in memories])

    api_key = "YOUR_GEMINI_KEY_HERE"

    response = requests.post(
        f"https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key={api_key}",
        json={
            "contents": [{
                "parts": [{
                    "text": f"You know this about the user:\n{memory_text}\n\nUsersays: {your_message}:"
                }]
            }]

        }

    )

    result = response.json()
    # Handle potential API errors where 'candidates' might not be present
    if 'candidates' not in result:
        print("API response did not contain 'candidates'. Full response:")
        print(result)
        return "Error: Could not get a response from Gemini."
    return result['candidates'] [0] ['content'] ['parts'] [0] ['text']

# TEST
response = chat_with_anastasiya("Who am I and what am I building ?")
print(response)

import requests
import json

# Assuming api_key is defined from the previous cell or manually set here
api_key = "YOUR_GEMINI_KEY_HERE"

list_models_url = f"https://generativelanguage.googleapis.com/v1/models?key={api_key}"
response_models = requests.get(list_models_url)

if response_models.ok:
    models_data = response_models.json()
    print("Available Gemini Models:")
    for model in models_data.get('models', []):
        print(f"- Name: {model.get('name')}, Display Name: {model.get('displayName')}, Supported Methods: {model.get('supportedGenerationMethods')}")
else:
    print(f"Failed to list models. Status: {response_models.status_code}, Response: {response_models.text}")